pdb: GLY72_2lyz # GLY72_2lyz

backup: True
backup_folder: pastRuns/

reference_rmsf: results/2lyz_6ns_at_400K_rmsf.csv
change_frequency: ../analysis/data/frequencies_500.csv



foldX_installation_folder: /home/filippo/Documents/foldx5/foldx5_1Linux64
reference_sequence:   KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL
most_common_sequence: KVFERCELARALKRLGLDGYRGYSLANWVCLAKWESNYNTQATNYNTDGSSTDYGIQQINSWWWCNDGKTPSANNACIICCSLLLSDDITQAVCCAKRVVDDPGGIAAWVAWRNCCQNDDLSWYRGGCZ # the Z means no amminoacid

namd:
  temperature: 313
  dcdfreq: 5000
  run: 1000000  # 2ns

blast:
  email: filippo.mininno@mail.polimi.it
  alignments: 100
  fasta_query: KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL
